services:
  minigame-postgres:
    container_name: minigame-postgres
    image: postgres:16
    restart: always
    volumes:
      - minigame-postgres:/data/minigame/postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: gogo_minigame
    ports:
      - '5432:5432'

  minigame-redis:
    container_name: minigame-redis
    image: redis:6
    restart: always
    volumes:
      - minigame-redis:/data/minigame/redis
    ports:
      - '6379:6379'

  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - '2181:2181'

  kafka:
    image: wurstmeister/kafka:2.12-2.5.0
    container_name: kafka
    ports:
      - '9092:9092'
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - zookeeper

volumes:
  minigame-postgres:
  minigame-redis:
