services:
  gogo-minigame-stage:
    container_name: gogo-minigame-stage
    build:
      dockerfile: Dockerfile
      context: .
    env_file:
      - .env
    ports:
      - "8086:8086"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8086/minigame/health"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 10s
    restart: on-failure
