[tool.poetry]
name = "gogo-minigame"
version = "0.1.0"
description = ""
authors = ["Jueuunn7 <wndmsrla1234@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.13"
django = "^5.1.6"
django-ninja = "^1.3.0"
django-ninja-extra = "^0.22.3"
psycopg2-binary = "^2.9.10"
pytest-django = "^4.9.0"
py-eureka-client = "^0.11.13"
channels = "^4.2.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
